# Generated by Django 3.1.4 on 2020-12-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Catagories',
            },
        ),
        migrations.CreateModel(
            name='Subcatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcatagories', to='api.catagory')),
            ],
            options={
                'verbose_name': 'Subcatagories',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('published', models.BooleanField(default=False)),
                ('subcatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='api.subcatagory')),
            ],
            options={
                'verbose_name': 'Ads',
            },
        ),
    ]
