# Generated by Django 3.1.4 on 2020-12-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ad_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterModelOptions(
            name='catagory',
            options={'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterModelOptions(
            name='subcatagory',
            options={'verbose_name_plural': 'Subcatagories'},
        ),
    ]
