# Generated by Django 3.1.4 on 2020-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201214_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='date_added',
            field=models.DateField(),
        ),
    ]
