# Generated by Django 3.1.4 on 2020-12-15 09:37

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201215_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='date_added',
        ),
        migrations.AddField(
            model_name='ad',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 9, 37, 3, 201202, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ad',
            name='time_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
