# Generated by Django 3.1.4 on 2020-12-15 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201215_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='subcatagory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='api.subcatagory'),
        ),
    ]
